### ISSUE TITLE
umiVar crashes without exception

### ISSUE THREAD

**Issue by leonschuetz** [imgag/umiVar#10]
It seems that samtools fails on some cigar-Strings and crashes. umiVar also reports errors, but contiunes without exception. This results in an output file which include only variants up to this point.

log:

> Stderr of '/mnt/storage1/users/ahschul1/git/umiVar2//venv/bin/python':
    [mpileup] 1 samples in 1 input files
    <mpileup> Set max per-file depth to 8000
    samtools: sam.c:2117: resolve_cigar2: Assertion `k < c->n_cigar' failed.
    Aborted (core dumped)
    Traceback (most recent call last):
      File "/mnt/storage1/users/ahschul1/git/umiVar2/pileup_parser.py", line 408, in <module>
        main()
      File "/mnt/storage1/users/ahschul1/git/umiVar2/pileup_parser.py", line 400, in main
        info = pileup_info(pileup_line, min_bq)
      File "/mnt/storage1/users/ahschul1/git/umiVar2/pileup_parser.py", line 98, in pileup_info
        base_quality = ord(qualities[q_pos]) - 33
    IndexError: string index out of range
    [mpileup] 1 samples in 1 input files
    <mpileup> Set max per-file depth to 8000
    [mpileup] 1 samples in 1 input files
    <mpileup> Set max per-file depth to 8000
    [mpileup] 1 samples in 1 input files
    <mpileup> Set max per-file depth to 8000
    Traceback (most recent call last):
      File "/mnt/storage1/users/ahschul1/git/umiVar2/variant_caller.py", line 602, in <module>
        parse_pileup_statistics()
      File "/mnt/storage1/users/ahschul1/git/umiVar2/variant_caller.py", line 325, in parse_pileup_statistics
        singleton_ref_depth = singleton_dp[locus_id][ref_nucleotide]
    KeyError: 'chr10_104377163'
    Saving 7 x 7 in image
    Saving 7 x 7 in image
    Saving 7 x 7 in image
    Saving 7 x 7 in image
    Saving 7 x 7 in image

affected samples: nearly all ARO-16 samples (e.g. Sample_I18D035bLB2_01)

**Comment by leonschuetz** [comment]
Error caused by old samtools version, error handling fixed in 0e4f8f71015cbd8d49d91594bb1fb46c46860bff
