### ISSUE TITLE
support tumor only samples for select_monitoring_variants.py?

### ISSUE THREAD

**Issue by leonschuetz** [imgag/umiVar#15]
Currently only tumor-normal VCFs are supported.

**Comment by leonschuetz** [comment]
Current error:
```
Stderr of '..../git/umiVar2//venv/bin/python':
    Traceback (most recent call last):
      File "..../git/umiVar2//select_monitoring_variants.py", line 402, in <module>
        main()
      File "..../git/umiVar2//select_monitoring_variants.py", line 396, in main
        evaluator.evaluate_variants(input_ref_file)
      File "..../git/umiVar2//select_monitoring_variants.py", line 131, in evaluate_variants
        tumor_sample = vcf_column[10].split(":")
    IndexError: list index out of range
```
