### ISSUE TITLE
IndexError in barcode_correction.py

### ISSUE THREAD

**Issue by caspargross** [imgag/umiVar#3]
Reproduce:

```
cd /mnt/users/ahgrosc1/projects/covid_umi/samples
python3 /mnt/users/ahgrosc1/tools/umivar2//barcode_correction.py --infile Sample_20076Pos_01/virus/20076Pos_01_position_sorted.bam --outfile Sample_20076Pos_01/dedup/20076Pos_01_corrected.bam
```

Error Message:
``` 
Traceback (most recent call last):
  File "/mnt/users/ahgrosc1/tools/umivar2//barcode_correction.py", line 587, in <module>
    main()
  File "/mnt/users/ahgrosc1/tools/umivar2//barcode_correction.py", line 419, in main
    bc = extract_barcode(read, args.barcodes)  # Extract the barcode
  File "/mnt/users/ahgrosc1/tools/umivar2//barcode_correction.py", line 39, in extract_barcode
    bc2 = barcode_entry.split(',')[1]
IndexError: list index out of range
```

**Comment by caspargross** [comment]
79fb7a5705937b35bba3d7c5872f8c1c89c2ab29
