### ISSUE TITLE
Empty variant output

### ISSUE THREAD

**Issue by caspargross** [imgag/umiVar#4]
```
Traceback (most recent call last):
  File "/mnt/storage1/users/ahgrosc1/tools/umivar2/variant_caller.py", line 487, in <module>
    parse_pileup_statistics()
  File "/mnt/storage1/users/ahgrosc1/tools/umivar2/variant_caller.py", line 187, in parse_pileup_statistics
    sequence_context = in_fasta.fetch(chrom, int(pos) - (num_bases + 1), int(pos) + num_bases)
  File "pysam/libcfaidx.pyx", line 290, in pysam.libcfaidx.FastaFile.fetch
  File "pysam/libcutils.pyx", line 252, in pysam.libcutils.parse_region
ValueError: start out of range (-5)
```

**Comment by caspargross** [comment]
Error in Pysam when fetching sequences from chromosome edges. Fixed in commit 3bdb1e6
